### ISSUE TITLE
Crash when exporting to pdf

### ISSUE THREAD

**Issue by angrykoala** [atareao/utext#1]
Crash in Ubuntu 16.04 when exporting markdown to pdf, markdown to html working fine
Error:
`utext crashed with AttributeError in on_menu_export(): 'uText' object has no attribute 'html_content'`

Tried exporting 3 times, 2 crashed, the other simply didn't created any pdf

the text exported was minimun:

``` markdown
hello
hello
```

**Comment by atareao** [comment]
Thanks. I found the bug. I released new version to fix the bug.

Best regards.
